// build.rs - Production-ready build script for Flan T5 tokenizer
use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;
use anyhow::{Result, Context};
use serde::Deserialize;
use serde_json::Value;

// Correct structures for Flan T5 tokenizer JSON format
#[derive(Deserialize)]
#[allow(dead_code)]
struct TokenizerConfig {
    model: ModelConfig,
    #[serde(default)]
    added_tokens: Vec<AddedToken>,
    #[serde(default)]
    normalizer: Option<Value>,
    #[serde(default)]
    pre_tokenizer: Option<PreTokenizer>,
    #[serde(default)]
    post_processor: Option<Value>,
}

#[derive(Deserialize)]
struct ModelConfig {
    #[serde(rename = "type")]
    model_type: String,
    // CRITICAL: vocab is actually Vec<(String, f64)> where index = token ID
    vocab: Vec<(String, f64)>,
    #[serde(default)]
    unk_id: Option<u32>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct AddedToken {
    id: u32,
    content: String,
    single_word: bool,
    lstrip: bool,
    rstrip: bool,
    normalized: bool,
    special: bool,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct PreTokenizer {
    #[serde(rename = "type")]
    tokenizer_type: String,
    replacement: String,
    add_prefix_space: bool,
}

const TOKENIZER_JSON: &str = "flan_t5_small_tokenizer.json";
const METASPACE_REPLACEMENT: &str = "▁";

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed={}", TOKENIZER_JSON);
    
    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("tokenizer_data.rs");
    
    let tokenizer_path = Path::new(TOKENIZER_JSON);
    if !tokenizer_path.exists() {
        return Err(anyhow::anyhow!(
            "Tokenizer file not found: {}. Please ensure {} is in the project root.",
            TOKENIZER_JSON, TOKENIZER_JSON
        ));
    }
    
    let config = parse_tokenizer_json(tokenizer_path)?;
    
    // Validate the tokenizer configuration
    validate_config(&config)?;
    
    generate_tokenizer_data(&dest_path, config)?;
    
    println!("cargo:warning=Successfully generated tokenizer data with {} tokens", 32128);
    Ok(())
}

fn parse_tokenizer_json(path: &Path) -> Result<TokenizerConfig> {
    let file = File::open(path)
        .with_context(|| format!("Failed to open tokenizer file: {:?}", path))?;
    
    let config: TokenizerConfig = serde_json::from_reader(file)
        .with_context(|| "Failed to parse tokenizer JSON")?;
    
    Ok(config)
}

fn validate_config(config: &TokenizerConfig) -> Result<()> {
    // Validate model type
    if config.model.model_type != "Unigram" {
        return Err(anyhow::anyhow!(
            "Expected Unigram model type, got: {}",
            config.model.model_type
        ));
    }
    
    // Validate vocabulary size
    let vocab_size = config.model.vocab.len();
    if vocab_size != 32100 && vocab_size != 32128 {
        // Accept both sizes as some versions may differ slightly
        return Err(anyhow::anyhow!(
            "Expected 32100 or 32128 tokens, got: {}",
            vocab_size
        ));
    }
    
    // Validate unk_id
    if config.model.unk_id != Some(2) {
        return Err(anyhow::anyhow!(
            "Expected unk_id to be 2, got: {:?}",
            config.model.unk_id
        ));
    }
    
    Ok(())
}

fn generate_tokenizer_data(dest_path: &Path, config: TokenizerConfig) -> Result<()> {
    let file = File::create(dest_path)?;
    let mut writer = BufWriter::new(file);
    
    writeln!(writer, "// Auto-generated by build.rs - DO NOT EDIT")?;
    writeln!(writer, "// Generated from: {}", TOKENIZER_JSON)?;
    writeln!(writer)?;
    
    // Generate imports
    writeln!(writer, "use phf::{{phf_map, Map}};")?;
    writeln!(writer, "use once_cell::sync::Lazy;")?;
    writeln!(writer, "use std::collections::HashMap;")?;
    writeln!(writer)?;
    
    // Process vocabulary more efficiently - avoid cloning
    let vocab_size = config.model.vocab.len();
    let mut special_token_ids = Vec::new();
    
    // Identify special tokens without creating intermediate maps
    for (id, (token, score)) in config.model.vocab.iter().enumerate() {
        if *score == 0.0 {
            special_token_ids.push((token.as_str(), id as u32));
        }
    }
    
    // Generate vocabulary constants
    generate_vocab_constants(&mut writer, vocab_size, &special_token_ids)?;
    
    // Generate forward mapping (token -> id) using PHF
    generate_forward_mapping(&mut writer, &config.model.vocab)?;
    
    // Generate reverse mapping (id -> token) as chunked arrays
    generate_reverse_mapping(&mut writer, &config.model.vocab)?;
    
    // Generate score mapping
    generate_score_mapping(&mut writer, &config.model.vocab)?;
    
    // Generate helper functions
    generate_helper_functions(&mut writer)?;
    
    // Generate pre-tokenizer configuration
    generate_pretokenizer_config(&mut writer, &config)?;
    
    writer.flush()?;
    Ok(())
}

fn generate_vocab_constants(
    writer: &mut BufWriter<File>,
    vocab_size: usize,
    special_tokens: &[(&str, u32)],
) -> Result<()> {
    writeln!(writer, "// Vocabulary size")?;
    writeln!(writer, "pub const VOCAB_SIZE: usize = {};", vocab_size)?;
    writeln!(writer)?;
    
    // Extract specific special tokens
    let pad_id = special_tokens.iter()
        .find(|(token, _)| *token == "<pad>")
        .map(|(_, id)| *id)
        .unwrap_or(0);
    let eos_id = special_tokens.iter()
        .find(|(token, _)| *token == "</s>")
        .map(|(_, id)| *id)
        .unwrap_or(1);
    let unk_id = special_tokens.iter()
        .find(|(token, _)| *token == "<unk>")
        .map(|(_, id)| *id)
        .unwrap_or(2);
    
    writeln!(writer, "// Special token IDs")?;
    writeln!(writer, "pub const PAD_TOKEN_ID: u32 = {};", pad_id)?;
    writeln!(writer, "pub const EOS_TOKEN_ID: u32 = {};", eos_id)?;
    writeln!(writer, "pub const UNK_TOKEN_ID: u32 = {};", unk_id)?;
    writeln!(writer)?;
    
    writeln!(writer, "// Special token strings")?;
    writeln!(writer, "pub const PAD_TOKEN: &str = \"<pad>\";")?;
    writeln!(writer, "pub const EOS_TOKEN: &str = \"</s>\";")?;
    writeln!(writer, "pub const UNK_TOKEN: &str = \"<unk>\";")?;
    writeln!(writer)?;
    
    // Generate extra_id token constants
    writeln!(writer, "// Extra ID tokens")?;
    writeln!(writer, "pub const EXTRA_ID_START: u32 = 32000;")?;
    writeln!(writer, "pub const EXTRA_ID_END: u32 = 32099;")?;
    writeln!(writer, "pub const NUM_EXTRA_IDS: usize = 100;")?;
    writeln!(writer)?;
    
    Ok(())
}

fn generate_forward_mapping(
    writer: &mut BufWriter<File>,
    vocab: &[(String, f64)],
) -> Result<()> {
    writeln!(writer, "// Forward mapping: token -> id")?;
    writeln!(writer, "pub static TOKEN_TO_ID: Map<&'static str, u32> = phf_map! {{")?;
    
    for (id, (token, _)) in vocab.iter().enumerate() {
        writeln!(writer, "    {:?} => {}u32,", token, id)?;
    }
    
    writeln!(writer, "}};")?;
    writeln!(writer)?;
    
    Ok(())
}

fn generate_reverse_mapping(
    writer: &mut BufWriter<File>,
    vocab: &[(String, f64)],
) -> Result<()> {
    writeln!(writer, "// Reverse mapping: id -> token (chunked for compile-time limits)")?;
    
    const CHUNK_SIZE: usize = 8192;
    let max_id = vocab.len() - 1;
    let num_chunks = (max_id + CHUNK_SIZE) / CHUNK_SIZE;
    
    // Create chunks
    for chunk_idx in 0..num_chunks {
        let start_id = chunk_idx * CHUNK_SIZE;
        let end_id = ((chunk_idx + 1) * CHUNK_SIZE).min(vocab.len());
        
        writeln!(writer, "const ID_TO_TOKEN_CHUNK_{}: [Option<&'static str>; {}] = [",
            chunk_idx, CHUNK_SIZE)?;
        
        for id in start_id..start_id + CHUNK_SIZE {
            if id < end_id {
                writeln!(writer, "    Some({:?}),", &vocab[id].0)?;
            } else {
                writeln!(writer, "    None,")?;
            }
        }
        
        writeln!(writer, "];")?;
        writeln!(writer)?;
    }
    
    // Generate lookup function
    writeln!(writer, "pub fn id_to_token(id: u32) -> Option<&'static str> {{")?;
    writeln!(writer, "    let chunk_idx = (id as usize) / {};", CHUNK_SIZE)?;
    writeln!(writer, "    let chunk_offset = (id as usize) % {};", CHUNK_SIZE)?;
    writeln!(writer, "    match chunk_idx {{")?;
    
    for chunk_idx in 0..num_chunks {
        writeln!(writer, "        {} => ID_TO_TOKEN_CHUNK_{}[chunk_offset],",
            chunk_idx, chunk_idx)?;
    }
    
    writeln!(writer, "        _ => None,")?;
    writeln!(writer, "    }}")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;
    
    Ok(())
}

fn generate_score_mapping(
    writer: &mut BufWriter<File>,
    vocab: &[(String, f64)],
) -> Result<()> {
    writeln!(writer, "// Token scores (log probabilities)")?;
    writeln!(writer, "pub static TOKEN_SCORES: Map<&'static str, f64> = phf_map! {{")?;
    
    for (token, score) in vocab {
        writeln!(writer, "    {:?} => {}f64,", token, score)?;
    }
    
    writeln!(writer, "}};")?;
    writeln!(writer)?;
    
    // Generate score lookup by ID
    writeln!(writer, "pub fn get_token_score(token: &str) -> f64 {{")?;
    writeln!(writer, "    TOKEN_SCORES.get(token).copied().unwrap_or(0.0)")?;
    writeln!(writer, "}}")?;
    writeln!(writer)?;
    
    Ok(())
}

fn generate_helper_functions(writer: &mut BufWriter<File>) -> Result<()> {
    writeln!(writer, "// Helper functions for text processing")?;
    writeln!(writer)?;
    
    // Unicode category functions (compatible with rust_tokenizers)
    writeln!(writer, r#"/// Check if a character is a control character"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn is_control(c: char) -> bool {{"#)?;
    writeln!(writer, r#"    matches!(c as u32, 0x0000..=0x001F | 0x007F..=0x009F)"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    writeln!(writer, r#"/// Check if a character is whitespace"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn is_whitespace(c: &char) -> bool {{"#)?;
    writeln!(writer, r#"    matches!(*c, ' ' | '\t' | '\n' | '\r' | '\x0B' | '\x0C' | '\u{{00A0}}' | '\u{{FEFF}}' | '\u{{200B}}')"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    writeln!(writer, r#"/// Check if a character is a CJK character"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn is_cjk_char(c: char) -> bool {{"#)?;
    writeln!(writer, r#"    matches!(c as u32,"#)?;
    writeln!(writer, r#"        0x4E00..=0x9FFF   | // CJK Unified Ideographs"#)?;
    writeln!(writer, r#"        0x3400..=0x4DBF   | // CJK Extension A"#)?;
    writeln!(writer, r#"        0x20000..=0x2A6DF | // CJK Extension B"#)?;
    writeln!(writer, r#"        0x2A700..=0x2B73F | // CJK Extension C"#)?;
    writeln!(writer, r#"        0x2B740..=0x2B81F | // CJK Extension D"#)?;
    writeln!(writer, r#"        0x2B820..=0x2CEAF | // CJK Extension E"#)?;
    writeln!(writer, r#"        0xF900..=0xFAFF   | // CJK Compatibility Ideographs"#)?;
    writeln!(writer, r#"        0x2F800..=0x2FA1F   // CJK Compatibility Supplement"#)?;
    writeln!(writer, r#"    )"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    writeln!(writer, r#"/// Check if a character is punctuation"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn is_punctuation(c: char) -> bool {{"#)?;
    writeln!(writer, r#"    matches!(c,"#)?;
    writeln!(writer, r#"        '!' | '"' | '#' | '$' | '%' | '&' | '\'' | '(' | ')' | '*' |"#)?;
    writeln!(writer, r#"        '+' | ',' | '-' | '.' | '/' | ':' | ';' | '<' | '=' | '>' |"#)?;
    writeln!(writer, r#"        '?' | '@' | '[' | '\\' | ']' | '^' | '_' | '`' | '{{' | '|' |"#)?;
    writeln!(writer, r#"        '}}' | '~' | '¿' | '¡' | '§' | '¶' | '†' | '‡' | '•' | '…' |"#)?;
    writeln!(writer, r#"        '‰' | '′' | '″' | '‹' | '›' | '„' | '\u{{2018}}' | '\u{{2019}}' |"#)?;
    writeln!(writer, r#"        '—' | '–' | '©' | '®' | '™' | '°' | '¢' | '£' | '¥' | '€'"#)?;
    writeln!(writer, r#"    )"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    // Get extra_id token helper
    writeln!(writer, r#"/// Get extra_id token for a given index (0-99)"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn get_extra_id_token(index: u32) -> Option<String> {{"#)?;
    writeln!(writer, r#"    if index < 100 {{"#)?;
    writeln!(writer, r#"        Some(format!("<extra_id_{{}}>", index))"#)?;
    writeln!(writer, r#"    }} else {{"#)?;
    writeln!(writer, r#"        None"#)?;
    writeln!(writer, r#"    }}"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    // Get extra_id token ID helper
    writeln!(writer, r#"/// Get token ID for extra_id token"#)?;
    writeln!(writer, r#"#[inline]"#)?;
    writeln!(writer, r#"pub fn get_extra_id_token_id(index: u32) -> Option<u32> {{"#)?;
    writeln!(writer, r#"    if index < 100 {{"#)?;
    writeln!(writer, r#"        Some(32099 - index)"#)?;
    writeln!(writer, r#"    }} else {{"#)?;
    writeln!(writer, r#"        None"#)?;
    writeln!(writer, r#"    }}"#)?;
    writeln!(writer, r#"}}"#)?;
    writeln!(writer)?;
    
    Ok(())
}

fn generate_pretokenizer_config(
    writer: &mut BufWriter<File>,
    config: &TokenizerConfig,
) -> Result<()> {
    writeln!(writer, "// Pre-tokenizer configuration")?;
    
    if let Some(pre_tokenizer) = &config.pre_tokenizer {
        writeln!(writer, "pub const METASPACE_REPLACEMENT: &str = {:?};", pre_tokenizer.replacement)?;
        writeln!(writer, "pub const ADD_PREFIX_SPACE: bool = {};", pre_tokenizer.add_prefix_space)?;
    } else {
        writeln!(writer, "pub const METASPACE_REPLACEMENT: &str = {:?};", METASPACE_REPLACEMENT)?;
        writeln!(writer, "pub const ADD_PREFIX_SPACE: bool = true;")?;
    }
    writeln!(writer)?;
    
    // Generate special token set for fast lookup without cloning
    writeln!(writer, "// Special token set for fast lookup")?;
    writeln!(writer, "pub static SPECIAL_TOKEN_SET: Lazy<HashMap<u32, &'static str>> = Lazy::new(|| {{")?;
    writeln!(writer, "    let mut map = HashMap::new();")?;
    
    for token in &config.added_tokens {
        if token.special {
            writeln!(writer, "    map.insert({}, {:?});", token.id, &token.content)?;
        }
    }
    
    writeln!(writer, "    map")?;
    writeln!(writer, "}});")?;
    writeln!(writer)?;
    
    Ok(())
}